### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by leecollings** [OwlCarousel2/OwlCarousel2#1618]
Having just updated the JS file on my local site to 2.2.0, I am now seeing the following console error message, and experiencing each slide on my carousels to appear as inline items one after the other.

```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at e.setup (http://bellavou.local/wp-content/themes/bellavou/js/owl.carousel.min.js:6:6111)
    at new e (http://bellavou.local/wp-content/themes/bellavou/js/owl.carousel.min.js:6:886)
    at HTMLDivElement.<anonymous> (http://bellavou.local/wp-content/themes/bellavou/js/owl.carousel.min.js:6:20951)
    at Function.each (http://bellavou.local/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:2881)
    at a.fn.init.each (http://bellavou.local/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:846)
    at a.fn.init.a.fn.owlCarousel (http://bellavou.local/wp-content/themes/bellavou/js/owl.carousel.min.js:6:20890)
    at http://bellavou.local/wp-content/themes/bellavou/js/init.js:300:37
    at http://bellavou.local/wp-content/themes/bellavou/js/init.js:441:3
```

Note: It's referencing line 526 on the full version.

Regarding my init.js file, line 300 features this:
```
    // Sidebar thumbnails
    $("#image-compare-nav-sidebar").owlCarousel({
        items:3,
        margin:10,
        nav:false,
        dots:true
    });
```

And line 441 looks like this:
`})(jQuery);`

What's causing the error in this new version that wasn't happening in the older one?

**Comment by leecollings** [comment]
Just to add to this, after seeing the previous issue regarding the class attribute, when I add a class to each div where I'm referencing an ID, it doesn't fix the issue, but instead just adds `owl-loaded` to the class list.

It's very hard to describe, but with the class attribute added, when the slider appears to 'slide', the long vertical block of slides moves across the page. (see my screenshot)
![bv_owlcarousel-2 2 0_bug](https://cloud.githubusercontent.com/assets/6681733/19853076/f71c9796-9f5e-11e6-82a5-0f652ba4739f.jpg)

**Comment by leecollings** [comment]
This is now fixed, after reading the docs I added `owl-carousel` to the selector, and that seemed to kick in. However, the `nav:false` option doesn't seem to be working, but I will open that as a new issue if needed.
