### ISSUE TITLE
NPM Error Occurred When Compiling

### ISSUE THREAD

**Issue by WeeHong** [OwlCarousel2/OwlCarousel2#2124]
Hello,

I am actually facing an issue everything I tried to run `npm run dev`

This is the error I am facing,

```
ERROR in ./node_modules/owl.carousel/dist/assets/owl.video.play.png
Module build failed: Error: spawn /var/www/blissbox/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/css-loader!./node_modules/owl.carousel/dist/assets/owl.carousel.css 6:3522-3553
 @ ./node_modules/owl.carousel/dist/assets/owl.carousel.css
 @ ./resources/assets/js/frontend/about.js
 @ multi ./resources/assets/js/frontend/about.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/weehong/.npm/_logs/2017-11-10T08_01_28_836Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/weehong/.npm/_logs/2017-11-10T08_01_28_849Z-debug.log
```

I'm not sure why it always prompt me this error on my production website while my local is working fine.

**Comment by bugwheels94** [comment]
Hi! You need file-loader when compiling CSS

**Comment by WeeHong** [comment]
@bugwheels94 

Why I no need a file-loader when I run it on local?

**Comment by bugwheels94** [comment]
Don't do it then. Your wish.

**Comment by WeeHong** [comment]
@bugwheels94,

Lol. 

I just wondering it is needed on Linux OS environment but when it comes to Windows OS environment.

I thought it is the same `package.json`?

Hmm.

**Comment by bugwheels94** [comment]
I am not a dev at OwlCarousel and neither a dev from webpack. Just thought to help you out but not much info here. And, no idea about windows too.

**Comment by WeeHong** [comment]
@bugwheels94 

I see. Thank you so much.

By the way, I solve it after I use `npm rebuild` and run `npm run dev` after that command.
